const mongoose = require('mongoose');
const predictionSchema = new mongoose.Schema({
  fixtureId: { type: String, required: true },
  canonicalFixtureKey: { type: String },
  modelVersion: { type: String, required: true },
  calibrationVersion: { type: String, default: null },
  selectionVersion: { type: String, default: null },
  kickoff: { type: Date, required: true, index: true },
  league: { type: String, default: '' },
  homeTeam: { type: String, required: true },
  awayTeam: { type: String, required: true },
  homeTeamId: { type: String, default: null },
  awayTeamId: { type: String, default: null },
  canonicalProvider: { type: String, enum: ['sportmonks','bsd','sportsdb',null], default: null },
  providerIds: { type: mongoose.Schema.Types.Mixed, default: {} },
  publicationStatus: { type: String, enum: ['UNAVAILABLE','PICK','VALUE','NO_BET',null], default: null },
  publishedSelections: { type: [mongoose.Schema.Types.Mixed], default: [] },
  capturedAt: { type: Date, default: Date.now },
  homeLambda: Number,
  awayLambda: Number,
  dataQualityScore: Number,
  qualityDimensions: { type: mongoose.Schema.Types.Mixed, default: null },
  marketEvidence: { type: mongoose.Schema.Types.Mixed, default: null },
  xgProvenance: { type: mongoose.Schema.Types.Mixed, default: null },
  bttsDirection: { type: mongoose.Schema.Types.Mixed, default: null },
  probabilities: { type: mongoose.Schema.Types.Mixed, required: true },
  rawProbabilities: { type: mongoose.Schema.Types.Mixed, default: null },
  comparisonProbabilities: { type: mongoose.Schema.Types.Mixed, default: null },
  sportmonksEvidence: { type: mongoose.Schema.Types.Mixed, default: null },
  marketBoardSnapshot: { type: mongoose.Schema.Types.Mixed, default: null },
  strongestPick: { type: mongoose.Schema.Types.Mixed, default: null },
  topPicksSnapshot: { type: [mongoose.Schema.Types.Mixed], default: [] },
  v4Validation: { type: [mongoose.Schema.Types.Mixed], default: [] },
  closingLineSnapshot: { type: [mongoose.Schema.Types.Mixed], default: [] },
  closingLineCapturedAt: { type: Date, default: null },
  status: { type: String, enum: ['pending','settled'], default: 'pending', index: true },
  actual: { type: mongoose.Schema.Types.Mixed, default: null },
  settledAt: Date,
}, { minimize: false });
predictionSchema.index(
  { canonicalFixtureKey: 1, modelVersion: 1 },
  { unique: true, partialFilterExpression: { canonicalFixtureKey: { $type: 'string' } } }
);
module.exports = mongoose.model('PredictionSnapshot', predictionSchema);
